#ifndef __CALIBRATION_H__
#define __CAIBRATION_H__

#define CALIBRATION_ANALOG_REF 4.24f

#define CALIBRATION_SENSE_FACTOR 4.27f // 1/0.234166f 


#define CALIBRATION_MAX_VOLTAGE10MV 300.0f
#define CALIBRATION_MAIN_RESISTOR_VALUE 1

#endif //__CALIBRATION_H__