#ifndef __GLOBALCONFIG_H__
#define __GLOBALCONFIG_H__

#define DEBUG 1

#define INPUT_ROTARY_PIN_A 2 
#define INPUT_ROTARY_PIN_B 3
#define INPUT_ROTARY_PIN_SWITCH 8

#define INPUT_BUTTON_OK_PIN 6
#define INPUT_BUTTON_BACK_PIN 7

#define INPUT_ANALOG_REF_PIN    A0
#define INPUT_CURRENT_SENSE_PIN A1
#define INPUT_TEMPERATURE_PIN   A2
#define INPUT_VOLTAGE_SENSE_PIN A3



#define DCLOAD_VOLTAGE_SET_PIN 9
#define DCLOAD_FAN_OUTPUT_PIN 5 


#endif //__GLOBALCONFIG_H__